spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productos
  application:
    name: Tantelise-productosService
server:
  port: 8989
eureka:
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    statusPageUrlPath: /swagger-ui.html
security:
  basic:
    enabled: false
  oauth2:
    resource:
      user-info-uri: http://localhost:8081/usuarios/info
      prefer-token-info: true
signing:
  key: asda1231LO
logging:
  level:
    root: INFO
    cl.dramos: TRACE
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'