spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: productos
  application:
    name: Tantelise-productosService
server:
  port: 0
eureka:
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    statusPageUrlPath: /swagger-ui.html