spring:
  data:
    mongodb:
      host: "localhost"
      port: "27017"
      database: "productos"
  application:
    name: "Tantelise - Productos "
    
server:
  port: 8081
  
eureka:
  client:
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8080/eureka/

logging:
  level:
    root: ERROR
    org.springframework: WARN
    cl.tantelise:  TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
